name:                rest-example
version:             0.1.0.0
github:              "tmciver-mackey/rest-example"
license:             BSD3
author:              "Tim McIver"
maintainer:          "tmciver@mackeycorp.com"
copyright:           "2022 Tim McIver"

extra-source-files:
- README.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/tmciver-mackey/rest-example#readme>

dependencies:
- base >= 4.7 && < 5
- protolude
- aeson
- containers
- servant-server
- wai
- warp

library:
  source-dirs: src

executables:
  rest-example-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    - -Wall
    dependencies:
    - base
    - rest-example

tests:
  rest-example-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - base
    - rest-example
    - hspec
    - hspec-wai
    - hspec-wai-json
    - aeson
